=== daniel-le97/api/ui/.astro/collections/magnet.schema.json
{
  "$ref": "#/definitions/magnet",
  "definitions": {
    "magnet": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string"
          },
          "size": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "magnet": {
            "type": "string"
          }
        },
        "required": [
          "date",
          "size",
          "title",
          "magnet"
        ],
        "additionalProperties": false
      }
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== daniel-le97/api/scripts/data/17/2023.json
[{"date":"<tr>12-01-2023<td>3.4 GB</td><td>Emergency Information! Tune In NOW! High-Level Government Whistleblower Confirms Covid Vax Killing Millions!</td><td>magnet:?xt=urn:btih:7b03239df75842e6d2b9909c24c3c925537dd53f&#038;dn=12-01-2023%20Emergency%20Information%21%20Tune%20In%20NOW%21%20High-Level%20Government%20Whistleblower%20Confirms%20Covid%20Vax%20Killing%20Millions%21%20%E2%80%94%20FRIDAY.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","size":"<tr>12-03-2023<td>3.4 GB</td><td>Sunday Live Governments Arrest Whistleblowers Who Exposed COVID Jab Mass Deaths to the World — Alex Jones Responds!</td><td>magnet:?xt=urn:btih:d1e6bdbc44e3bb8b045cd66bfd7b9fc62a48e1c0&#038;dn=12-03-2023%20Sunday%20Live%20Governments%20Arrest%20Whistleblowers%20Who%20Exposed%20COVID%20Jab%20Mass%20Deaths%20to%20the%20World%20%E2%80%94%20Alex%20Jones%20Responds%21%20-%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","title":"<tr>12-04-2023<td>3.5 GB</td><td>WARNING! Mass Child Rape Confirmed! DHS Whistleblower Exposes Full Horror of Biden&#8217;s Massive Child Sex Trafficking Operation</td><td>magnet:?xt=urn:btih:cb5bf18d186b066a12b8b04748bae8e0517f083f&#038;dn=12-04-2023%20WARNING%21%20Mass%20Child%20Rape%20Confirmed%21%20DHS%20Whistleblower%20Exposes%20Full%20Horror%20of%20Biden%27s%20Massive%20Child%20Sex%20Trafficking%20Operation%20%E2%80%94%20MONDAY%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","magnet":"<tr>12-05-2023<td>3.3 GB</td><td>WORLD EXCLUSIVE Freed New Zealand Whistleblower Gives First Major Interview After Exposing Killer COVID Jabs</td><td>magnet:?xt=urn:btih:cec41ec3d88af9f682c6ccd14715c33deaa18a09&#038;dn=12-05-2023%20WORLD%20EXCLUSIVE%20Freed%20New%20Zealand%20Whistleblower%20Gives%20First%20Major%20Interview%20After%20Exposing%20Killer%20COVID%20Jabs%20%E2%80%94%20TUESDAY%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>"},{"date":"<tr>12-06-2023<td>3.2 GB</td><td>Liberty Movement Strikes Back! Paxton Suing State Department for Targeting Conservatives, Pfizer for Lying About Covid Jabs</td><td>magnet:?xt=urn:btih:fceb433e84f1b206a8ae6269befc6eeb0e2cb56c&#038;dn=12-06-2023%20Liberty%20Movement%20Strikes%20Back%21%20Paxton%20Suing%20State%20Department%20for%20Targeting%20Conservatives%2C%20Pfizer%20for%20Lying%20About%20Covid%20Jabs%20as%20Establishment%20Scrambles%20to%20Stop%20Trump%E2%80%99s%20%E2%80%9CRetribution%E2%80%9D%20%E2%80%94%20The%20Great%20Awakening%20is%20HERE.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","size":"<tr>12-07-2023<td>3.3 GB</td><td>Red Alert Broadcast! Biden Holds Planet Hostage, Threatens DIRECT WAR With Russia If Congress Doesn’t Deliver $106 Billion to Zelensky</td><td>magnet:?xt=urn:btih:721b0b8091fd4a03575450e739ff863f70fda107&#038;dn=12-07-2023%20Red%20Alert%20Broadcast%21%20Biden%20Holds%20Planet%20Hostage%2C%20Threatens%20DIRECT%20WAR%20With%20Russia%20If%20Congress%20Doesn%E2%80%99t%20Deliver%20%24106%20Billion%20to%20Zelensky%20%E2%80%94%20This%20Is%20Nuclear%20Blackmail%21%20%E2%80%94%20THURSDAY%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","title":"<tr>12-08-2023<td>3.2 GB</td><td>Is Elon Musk Set to Unban Alex Jones on X &#038; How Would This Change the Infowar</td><td>magnet:?xt=urn:btih:0b023767c851e99614efd648b2a32e8eb89cc046&#038;dn=12-08-2023%20Is%20Elon%20Musk%20Set%20to%20Unban%20Alex%20Jones%20on%20X%20%26%20How%20Would%20This%20Change%20the%20Infowar%20WATCH%20NOW%21%20%E2%80%94%20FRIDAY%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","magnet":"<tr>12-10-2023<td>3.5 GB</td><td>Alex Jones Interviews Elon Musk For 2+ Hours Live — Learn What Comes Next!</td><td>magnet:?xt=urn:btih:ed8831663f08713c7f03b9c607baf79df9809ff1&#038;dn=12-10-2023%20Alex%20Jones%20Interviews%20Elon%20Musk%20For%202%2B%20Hours%20Live%20%E2%80%94%20Learn%20What%20Comes%20Next%21%20%E2%80%94%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>"},{"date":"<tr>12-11-2023<td>3.4 GB</td><td>Total Infowar Victory! Alex Jones Drops Massive Truth Bombs to Millions of NEW Listeners on X! Globalists Are FREAKING OUT</td><td>magnet:?xt=urn:btih:070dbe9699bacdfbec19b4ae971a4c682ad80aa1&#038;dn=12-11-2023%20Total%20Infowar%20Victory%21%20Alex%20Jones%20Drops%20Massive%20Truth%20Bombs%20to%20Millions%20of%20NEW%20Listeners%20on%20X%21%20Globalists%20Are%20FREAKING%20OUT%2C%20Threatening%20Nuclear%20War%20%E2%80%94%20MONDAY%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","size":"<tr>12-12-2023<td>3.3 GB</td><td>It’s Official! NWO Puppet Zelensky Has Officially Lost the War!</td><td>magnet:?xt=urn:btih:09a6febaf89b9b274b8ae5fd25b351b95e5425e3&#038;dn=12-12-2023%20It%E2%80%99s%20Official%21%20NWO%20Puppet%20Zelensky%20Has%20Officially%20Lost%20the%20War%21%20Globalists%20Prepare%20to%20Trigger%20MASSIVE%20Cyber%20Attacks%20to%20Accelerate%20Planetary%20Destabilization%20%E2%80%94%20TUESDAY%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","title":"<tr>12-13-2023<td>3.4 GB</td><td>WW3 ALERT USNATO Officially Mobilizes Direct War Against Russia</td><td>magnet:?xt=urn:btih:693ea6f5229ccd6d7ba6b5c96046de7d03bbe941&#038;dn=12-13-2023%20WW3%20ALERT%20USNATO%20Officially%20Mobilizes%20Direct%20War%20Against%20Russia%20%E2%80%94%20WEDNESDAY%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","magnet":"<tr>12-14-2023<td>3.3 GB</td><td>Plan Announced for Ukraine to Enter NATO Potentially Triggering TOTAL WAR!</td><td>magnet:?xt=urn:btih:dec743d2c26964e950098ccca2f5501a2a8aefa3&#038;dn=12-14-2023%20Plan%20Announced%20for%20Ukraine%20to%20Enter%20NATO%20Potentially%20Triggering%20TOTAL%20WAR%21%20MUST%20WATCH%20FULL%20EMERGENCY%20BROADCAST.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>"},{"date":"<tr>12-15-2023<td>3.1 GB</td><td>EMERGENCY ALERT NATO Crosses Putin’s Red Line</td><td>magnet:?xt=urn:btih:eba1534ef15142d3f69fcfb8632f1a34a041b570&#038;dn=12-15-2023%20EMERGENCY%20ALERT%20NATO%20Crosses%20Putin%E2%80%99s%20Red%20Line%2C%20Accelerates%20Plan%20for%20Ukraine%20to%20Enter%20NATO%20as%20Both%20Sides%20Mobilize%20for%20TOTAL%20War%20-%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","size":"<tr>12-17-2023<td>2.5 GB</td><td>Full Sunday Broadcast Letitia James Confesses to Framing Donald Trump</td><td>magnet:?xt=urn:btih:08f7c25497c367acf0b45c73df290984410bfd07&#038;dn=12-17-2023%20Full%20Sunday%20Broadcast%20Letitia%20James%20Confesses%20to%20Framing%20Donald%20Trump%20in%20Staged%20New%20York%20Show%20Trial%20-%20The%20Alex%20Jones%20Show%20-%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","title":"<tr>12-18-2023<td>3.2 GB</td><td>Communist China Caught Funding Climate Change Cult</td><td>magnet:?xt=urn:btih:d6a2caca585c76da9803ee1c9c24c09f9cfd8254&#038;dn=12-18-2023%20Communist%20China%20Caught%20Funding%20Climate%20Change%20Cult%20In%20Effort%20to%20Cut%20Off%20West%E2%80%99s%20Energy%20%E2%80%94%20MUST%20WATCH%20%E2%80%94%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","magnet":"<tr>12-19-2023<td>3.2 GB</td><td>EMERGENCY BROADCAST US Border “Completely Overrun”</td><td>magnet:?xt=urn:btih:4523f6eb06365cd22d4e2e4b1b139c8d8d7d01f0&#038;dn=12-19-2023%20EMERGENCY%20BROADCAST%20US%20Border%20%E2%80%9CCompletely%20Overrun%E2%80%9D%20With%20Illegals%20From%20Around%20the%20World%20As%20the%20Totalitarian%20EU%20Moves%20to%20Kill%20Free%20Speech%20on%20X%21%20%E2%80%94%20TUESDAY.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>"},{"date":"<tr>12-20-2023<td>3.4 GB</td><td>EMERGENCY BROADCAST The Democratic Party Is Officially Establishing A Permanent Dictatorship</td><td>magnet:?xt=urn:btih:30c3801116e971412fdf07fba63ffd039c780b41&#038;dn=12-20-2023%20EMERGENCY%20BROADCAST%20The%20Democratic%20Party%20Is%20Officially%20Establishing%20A%20Permanent%20Dictatorship%20in%20America%21%20This%20Coup%20Is%20Not%20Just%20Against%20Trump%20But%20the%20American%20People%E2%80%99s%20Right%20to%20Elect%20Who%20They%20Want%20to%20Represent%20T.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","size":"<tr>12-27-2023<td>3.3 GB</td><td>Alex Jones Returns! WWIII, Collapsing Borders</td><td>magnet:?xt=urn:btih:4c180be2664d8b72dcb2090ffe26f8650afd2c51&#038;dn=12-27-2023%20Alex%20Jones%20Returns%21%20WWIII%2C%20Collapsing%20Borders%2C%20The%20Great%20Awakening%2C%20It%E2%80%99s%20All%20Going%20Down%20%E2%80%94%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","title":"<tr>12-28-2023<td>3.3 GB</td><td>Emergency Broadcast New American Civil War Openly Promoted</td><td>magnet:?xt=urn:btih:dd6095b423332f10778640c5fb2df9b5e16ecdb5&#038;dn=12-28-2023%20Emergency%20Broadcast%20New%20American%20Civil%20War%20Openly%20Promoted%20By%20Globalist%20Deep%20State%20%E2%80%93%20Americans%20Must%20Come%20Together%20%26%20Stop%20It%21%20%E2%80%93%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>","magnet":"<tr>12-29-2023<td>3.1 GB</td><td>FULL FRIDAY BROADCAST US Southern Border Now Under UN Control</td><td>magnet:?xt=urn:btih:548ed0c865daaf4125ae1b80b51ca9e4c7107fe8&#038;dn=12-29-2023%20FULL%20FRIDAY%20BROADCAST%20US%20Southern%20Border%20Now%20Under%20UN%20Control%2C%20WEF%20Announces%20Global%20AI%20Mind%20Control%20Initiative%20%E2%80%93%20FULL%20SHOW.mp4&#038;tr=https%3A%2F%2Fmagnetdl.com</td>"}]
